In [1]:
!nvidia-smi # smi - System Management Interface, Can be executed after changing runtime to GPU

Wed Apr  2 20:04:06 2025       
+-----------------------------------------------------------------------------------------+
| NVIDIA-SMI 550.54.15              Driver Version: 550.54.15      CUDA Version: 12.4     |
|-----------------------------------------+------------------------+----------------------+
| GPU  Name                 Persistence-M | Bus-Id          Disp.A | Volatile Uncorr. ECC |
| Fan  Temp   Perf          Pwr:Usage/Cap |           Memory-Usage | GPU-Util  Compute M. |
|                                         |                        |               MIG M. |
|=========================================+========================+======================|
|   0  Tesla T4                       Off |   00000000:00:04.0 Off |                    0 |
| N/A   41C    P8              9W /   70W |       0MiB /  15360MiB |      0%      Default |
|                                         |                        |                  N/A |
+-----------------------------------------+-----

In [2]:
import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
print(torch.__version__)

2.6.0+cu124


In [3]:
#Creating a tensor in Pytorch

In [4]:
Dim0Tensor = torch.tensor(7)
Dim0Tensor

tensor(7)

In [5]:
Dim0Tensor.ndim

0

In [6]:
Dim0Tensor.item() # Get tensor back as Python List

7

In [7]:
Dim1tensor = torch.tensor([2,3]) # Vector as 1 Dim Tensor
Dim1tensor

tensor([2, 3])

In [8]:
Dim1tensor.ndim

1

In [9]:
Dim1tensor.shape

torch.Size([2])

In [10]:
Dim2Tensor = torch.tensor([[1, 2, 3], [4, 5, 6]])
Dim2Tensor

tensor([[1, 2, 3],
        [4, 5, 6]])

In [11]:
Dim2Tensor.ndim

2

In [12]:
Dim2Tensor.shape

torch.Size([2, 3])

In [13]:
Dim2Tensor[0]

tensor([1, 2, 3])

In [14]:
Dim3Tensor = torch.tensor([[[1, 2, 3], [3, 4, 5]], [[7, 8, 9], [10, 11, 12]]])
Dim3Tensor

tensor([[[ 1,  2,  3],
         [ 3,  4,  5]],

        [[ 7,  8,  9],
         [10, 11, 12]]])

In [15]:
Dim3Tensor.ndim

3

In [16]:
Dim3Tensor[0,0,1]

tensor(2)

In [17]:
Dim3Tensor.shape

torch.Size([2, 2, 3])

### Random Tensors

random tensors are improtant because the way neural networks learn is that they start with tensors full of randon numbers and then adjust those random numbers to better represnt the data.

Start with random numbers --> look at data --> update random numbers -> look at data --> Update random numbers

In [18]:
#Create random tensor of size (3,4)

randomTensor = torch.rand(3,4)
randomTensor

tensor([[0.7504, 0.5394, 0.4264, 0.4844],
        [0.5681, 0.4769, 0.9455, 0.9742],
        [0.0947, 0.5685, 0.1045, 0.2547]])

In [19]:
#Create a random tensor with similar shape to an image tensor
random_image_tensor = torch.rand(size = (224, 224, 3))
random_image_tensor.shape, random_image_tensor.ndim

(torch.Size([224, 224, 3]), 3)

### Create Ones and Zeros Tensor

In [20]:
zeros  = torch.zeros(3,4)
zeros

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [21]:
torch.ones(3,4)

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [22]:
rand = torch.rand(size = (3,4))

In [23]:
rand * zeros

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

### Create a range of tensors and tensors-like

In [24]:
rangetensor = torch.arange(0,10, 2)

In [25]:
torch.zeros_like(rangetensor)

tensor([0, 0, 0, 0, 0])

In [26]:
torch.ones_like(rangetensor)

tensor([1, 1, 1, 1, 1])

### Tensor DataTypes

Tensor datatypes is one of the 3 big errors you'ii run into with pytorch and deep learning.

1. Tensor not right datatype
2. Tensor not right shape
3. tensor not on the right device

In [27]:
tensorparams = torch.tensor([3, 7, 8],dtype=None,requires_grad=False,device=None) # default dtype is int64, float 32, device is CPU
# requires_grad - wheather or not to track the gradients with this tensor operations
tensorparams

tensor([3, 7, 8])

In [28]:
tensorparams.dtype

torch.int64

In [29]:
tensorparams = torch.tensor([3.0, 7.0, 8.0],dtype=None,requires_grad=False,device=None) # default dtype is int64, float 16, device is CPU
tensorparams.dtype

torch.float32

In [30]:
# Converting the datatype of a tensor

tensorparams = tensorparams.type(torch.float16)

In [31]:
tensorparams.dtype

torch.float16

### Getting Information from tensors

1. tensor.dtype - to get datatype
2. tensor.device - to get device from a tensor
3. tensor.shape - to get shape from a tensor

In [32]:
some_tensor = torch.rand(3, 4)
some_tensor

tensor([[0.3066, 0.4471, 0.9444, 0.1247],
        [0.6412, 0.4351, 0.7370, 0.3872],
        [0.9841, 0.1491, 0.6622, 0.9586]])

In [33]:
#Find details about some tensor
print(some_tensor)
print(f"Shape of the Tensor : {some_tensor.shape}")
print(f"Size of the tensor : {some_tensor.size()}") # Size and shape will give the same result except the size is a function and shape is an attribute
print(f"Device of the tensor: {some_tensor.device}")
print(f"Dtype of the tensor: {some_tensor.dtype}")

tensor([[0.3066, 0.4471, 0.9444, 0.1247],
        [0.6412, 0.4351, 0.7370, 0.3872],
        [0.9841, 0.1491, 0.6622, 0.9586]])
Shape of the Tensor : torch.Size([3, 4])
Size of the tensor : torch.Size([3, 4])
Device of the tensor: cpu
Dtype of the tensor: torch.float32


### Manipulating Tensors

Tensor Operations Include:
1. Addition
2. Substraction
3. Multipication (element-wise)
4. Divison
5. Matrix Multiplication

In [34]:
# Create a tensor
tensor = torch.tensor([1, 2, 3])
tensor + 10

tensor([11, 12, 13])

In [35]:
tensor * 10

tensor([10, 20, 30])

In [36]:
tensor # as we haven't reassigned tensor will remain unchanged

tensor([1, 2, 3])

In [37]:
tensor - 10

tensor([-9, -8, -7])

In [38]:
# Try out pytorch inbuild functions
torch.mul(tensor, 10)

tensor([10, 20, 30])

In [39]:
torch.add(tensor, 10)

tensor([11, 12, 13])

### Matrix Multiplication

Two main ways of performing multipication in neural networks and deep learning:

1. Element-wise multiplication
2. Matrix multiplication (dot product)

In [40]:
#Element Wise Multiplication
print(tensor, "*", tensor)
print(f"Equals : {tensor * tensor}")

tensor([1, 2, 3]) * tensor([1, 2, 3])
Equals : tensor([1, 4, 9])


In [41]:
#Matrix Multiplication

torch.matmul(tensor, tensor)

tensor(14)

In [42]:
%%time
value = 0
for i in range(len(tensor)):
  value += tensor[i] * tensor[i]
print(value)

tensor(14)
CPU times: user 1.23 ms, sys: 43 µs, total: 1.27 ms
Wall time: 1.04 ms


In [43]:
%%time
torch.matmul(tensor, tensor)

CPU times: user 185 µs, sys: 34 µs, total: 219 µs
Wall time: 164 µs


tensor(14)

In [44]:
tensorA = torch.tensor([[1,2],[1,2],[1,2]])
torch.matmul(tensorA, tensorA.T)

tensor([[5, 5, 5],
        [5, 5, 5],
        [5, 5, 5]])

### Find the min, max, mean, sum, etc (tensor Aggregation)

In [45]:
tensor = torch.arange(0, 100, 6)
tensor

tensor([ 0,  6, 12, 18, 24, 30, 36, 42, 48, 54, 60, 66, 72, 78, 84, 90, 96])

In [46]:
torch.max(tensor), tensor.max()

(tensor(96), tensor(96))

In [47]:
torch.min(tensor), tensor.min()

(tensor(0), tensor(0))

In [48]:
torch.argmax(tensor), tensor.argmax()

(tensor(16), tensor(16))

In [49]:
torch.argmin(tensor), tensor.argmin()

(tensor(0), tensor(0))

In [50]:
torch.mean(tensor.type(torch.float))

tensor(48.)

In [51]:
torch.sum(tensor), tensor.sum()

(tensor(816), tensor(816))

### Reshaping, Stacking, Squeezing, UnSqueezing

* Reshaping - reshape an input tensor to a defined shape
* View - return a view of an input tensor of certain shape but keep the same memory as the original tensor
* Stacking - combine Multiple tensors on top of each other (vstack) or side by side (hstack)
* Squeeze - removes all '1' dimensions from a tensor
* Unsqueeze - add a '1' dimension to a target tensor
* Permute - Return a view of the input with dimensions permuted (swapped) in a certain way

In [52]:
import torch
x = torch.arange(1., 10.)
x, x.shape

(tensor([1., 2., 3., 4., 5., 6., 7., 8., 9.]), torch.Size([9]))

In [53]:
#Add an extra dimension
x_reshaped = x.reshape(3,3)
x_reshaped, x_reshaped.shape

(tensor([[1., 2., 3.],
         [4., 5., 6.],
         [7., 8., 9.]]),
 torch.Size([3, 3]))

In [54]:
#Channge the view - Changing z changes x (because a view of a tensor shares the same memory as the original)
z = x.view(1, 9)
z, z.shape

(tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.]]), torch.Size([1, 9]))

In [55]:
z[:, 0] = 5
z, x

(tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.]]),
 tensor([5., 2., 3., 4., 5., 6., 7., 8., 9.]))

In [56]:
#Stack Tensors on top of each other
x_stacked = torch.stack([x,x,x,x], dim = 0)
x_stacked

tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.],
        [5., 2., 3., 4., 5., 6., 7., 8., 9.],
        [5., 2., 3., 4., 5., 6., 7., 8., 9.],
        [5., 2., 3., 4., 5., 6., 7., 8., 9.]])

In [57]:
#Stack Tensors on top of each other
x_stacked = torch.stack([x,x,x,x], dim = 1)
x_stacked

tensor([[5., 5., 5., 5.],
        [2., 2., 2., 2.],
        [3., 3., 3., 3.],
        [4., 4., 4., 4.],
        [5., 5., 5., 5.],
        [6., 6., 6., 6.],
        [7., 7., 7., 7.],
        [8., 8., 8., 8.],
        [9., 9., 9., 9.]])

In [58]:
#torch.squeeze - removes all single dimensions from a tensor

tensor = torch.arange(1, 10)
tensor = tensor.reshape(1,1,9)
tensor, tensor.shape

(tensor([[[1, 2, 3, 4, 5, 6, 7, 8, 9]]]), torch.Size([1, 1, 9]))

In [59]:
torch.squeeze(tensor).shape

torch.Size([9])

In [60]:
x = torch.zeros(2,1,2,1,2)

In [61]:
x.squeeze()

tensor([[[0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.]]])

In [62]:
torch.squeeze(x, 0).shape

torch.Size([2, 1, 2, 1, 2])

In [63]:
squeezetensor = torch.squeeze(x, 1)
squeezetensor.shape

torch.Size([2, 2, 1, 2])

In [64]:
squeezetensor.unsqueeze(dim = 0).shape

torch.Size([1, 2, 2, 1, 2])

In [65]:
squeezetensor.unsqueeze(dim = 3).shape

torch.Size([2, 2, 1, 1, 2])

In [66]:
#torch.permute - rearranges the dimensions of the target in a specifed order
x_original = torch.rand(size = (224,224,3)) # [height, width, color_channels]
x_original.shape

torch.Size([224, 224, 3])

In [67]:
x_permuted = x_original.permute(dims = (1,2,0))
x_permuted.shape # Shifts axis 1 --> 0, 2 --> 1, 0 --> 2 [width, color_channels, height]

torch.Size([224, 3, 224])

In [68]:
x_original[0,0,0] = 123456
x_original[0,0,0], x_permuted[0,0,0]


(tensor(123456.), tensor(123456.))

### Pytorch Tensors and Numpy

Numpy is a popular scientific python numerical computing library.
And because of this, PyTorch has functionality to interact with it.

*   Data in Numpy, want in PyTorch tensor --> torch.from_numpy(ndarray)
*   PyTorch tensor --> Numpy --> torch.Tensor.numpy()

In [69]:
#Numpy Array to tensor

array = np.arange(1.0, 8.0)
tensor = torch.from_numpy(array)
array, tensor

(array([1., 2., 3., 4., 5., 6., 7.]),
 tensor([1., 2., 3., 4., 5., 6., 7.], dtype=torch.float64))

In [70]:
array.dtype

dtype('float64')

In [71]:
torch.arange(1.0, 8.0).dtype

torch.float32

In [72]:
#Change the value of array, What will this do to Tensor - Tensor Value doesn't changed
array = array + 1
array, tensor

(array([2., 3., 4., 5., 6., 7., 8.]),
 tensor([1., 2., 3., 4., 5., 6., 7.], dtype=torch.float64))

In [73]:
#Tensor to numpy
tensor = torch.ones(2,7)
numpy_tensor = tensor.numpy()
numpy_tensor, numpy_tensor.dtype

(array([[1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1.]], dtype=float32),
 dtype('float32'))

#Reproducability (Trying to take random out of random)

In Short how neural network learns:

Start with random numbers --> tensor operations --> update random numbers to try and make them better representation of the data --> again --> again --> again...

to reduce the randomness in neural networks, pytorch comes the concept of a random seed. Essentially what the random seed does is "flavour" the randomness.

In [74]:
tensorA = torch.rand(3, 4)
tensorB = torch.rand(3, 4)

print(tensorA)
print(tensorB)
tensorA == tensorB

tensor([[0.8250, 0.4690, 0.0021, 0.2778],
        [0.2051, 0.1933, 0.5702, 0.8502],
        [0.1460, 0.5069, 0.5667, 0.4807]])
tensor([[0.6464, 0.8159, 0.8354, 0.2815],
        [0.4573, 0.4061, 0.3462, 0.5833],
        [0.5767, 0.5703, 0.2523, 0.1564]])


tensor([[False, False, False, False],
        [False, False, False, False],
        [False, False, False, False]])

In [75]:
# Let's make some random but reproduciable tensors
import torch
#Set the random seed
RANDOM_SEED = 42

torch.manual_seed(RANDOM_SEED)
tensorA = torch.rand(3,4)

torch.manual_seed(RANDOM_SEED) # we need to call this every time we use rand to create random numbers.
tensorB = torch.rand(3,4)

print(tensorA)
print(tensorB)
print(tensorA == tensorB)


tensor([[0.8823, 0.9150, 0.3829, 0.9593],
        [0.3904, 0.6009, 0.2566, 0.7936],
        [0.9408, 0.1332, 0.9346, 0.5936]])
tensor([[0.8823, 0.9150, 0.3829, 0.9593],
        [0.3904, 0.6009, 0.2566, 0.7936],
        [0.9408, 0.1332, 0.9346, 0.5936]])
tensor([[True, True, True, True],
        [True, True, True, True],
        [True, True, True, True]])


### Running tensors and Pytorch Objects on the GPUs (and making faster computations)

GPUs = faster computations on numbers, thanks to CUDA + NVIDIA hardware + Pytorch working behind the scenes to make everything good

In [76]:
!nvidia-smi

Wed Apr  2 20:04:12 2025       
+-----------------------------------------------------------------------------------------+
| NVIDIA-SMI 550.54.15              Driver Version: 550.54.15      CUDA Version: 12.4     |
|-----------------------------------------+------------------------+----------------------+
| GPU  Name                 Persistence-M | Bus-Id          Disp.A | Volatile Uncorr. ECC |
| Fan  Temp   Perf          Pwr:Usage/Cap |           Memory-Usage | GPU-Util  Compute M. |
|                                         |                        |               MIG M. |
|=========================================+========================+======================|
|   0  Tesla T4                       Off |   00000000:00:04.0 Off |                    0 |
| N/A   41C    P8              9W /   70W |       0MiB /  15360MiB |      0%      Default |
|                                         |                        |                  N/A |
+-----------------------------------------+-----

### Check for GPU access with PyTorch

In [77]:
torch.cuda.is_available()

True

### For PyTorch since it's capable of running on the GPU or CPU, it's best practice to setup device agnostic code.

E.g., run on GPU if available, else default to CPU

In [78]:
#Setup Device agnostic Code
device = "cuda" if torch.cuda.is_available() else "cpu"
device

'cuda'

In [79]:
#Count number of Devices
torch.cuda.device_count()

1

### Putting tensors (and models) on the GPU
The Reason we want our tensors/models on the GPU is because using a GPU results in faster computations

In [80]:
tensor = torch.tensor([1,2,3], device = "cpu")
tensor, tensor.device

(tensor([1, 2, 3]), device(type='cpu'))

In [81]:
tensor = torch.tensor([1,2,3])
tensor, tensor.device

(tensor([1, 2, 3]), device(type='cpu'))

In [84]:
#Move Tensor to Gpu if available
tensor_gpu = tensor.to(device)
tensor_gpu

tensor([1, 2, 3], device='cuda:0')

In [87]:
#Moving Tensors to the CPU
#If tensor is on GPU, can't transform it to NumPy (Numpy won't work on GPU)
try:
 tensor_gpu.numpy()
except:
  print("can't convert cuda:0 device type tensor to numpy. Use Tensor.cpu() to copy the tensor to host memory first")

can't convert cuda:0 device type tensor to numpy. Use Tensor.cpu() to copy the tensor to host memory first


In [88]:
#To fix the GPU tensor with Numpy issue, we can first set it to the CPU
tensor_back_on_cpu = tensor_gpu.cpu().numpy()
tensor_back_on_cpu

array([1, 2, 3])

### Excercises and Extra-Curriculam